name: MeTTaLog CI

on:
  push:
    branches: [refactor-metta]
  pull_request:
    branches: [refactor-metta]
  workflow_dispatch:
jobs:
  mettalog-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.3'

    - name: Upgrade pip and install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy pyswip janus ansi2html junit2html

    - name: Install SWI-Prolog from PPA
      run: |
        sudo apt-get remove -y swi-prolog swi-prolog-core swi-prolog-nox swi-prolog-x || true
        sudo apt-get update
        sudo apt-add-repository ppa:swi-prolog/stable -y
        sudo apt-get update
        sudo apt-get install -y swi-prolog

    - name: Install MeTTaLog (runs INSTALL.sh)
      run: |
        git clone https://github.com/eyuuab/metta-wam --depth 1
        cd metta-wam
        chmod +x ./INSTALL.sh
        bash -c "source ./INSTALL.sh --allow-system-modifications"


        # Export real paths (with expanded $PWD and $PATH)
        echo "PATH=${PWD}/venv/bin:${PATH}" >> $GITHUB_ENV
        echo "PYTHONPATH=${PWD}/python:${PWD}/tests/python_compat/metta-motto" >> $GITHUB_ENV
        echo "SWIPL_BOOT_FLAGS=--no-pce" >> $GITHUB_ENV
        echo "METTALOG_DIR=${PWD}" >> $GITHUB_ENV
    

    - name: Debug mettalog installation
      run: |
        echo "Looking inside venv/bin"
        ls -la metta-wam/venv/bin
        echo "Trying to locate mettalog"
        find metta-wam -type f -name "mettalog"
        which mettalog
 
    - name: Run MeTTaLog Tests
      run: |
        which mettalog  # Show full path if available
        python3 scripts/run-tests.py