name: metta-run CI

on:
  push:
    branches:
      - refactor-metta
  pull_request:
    branches:
      - refactor-metta

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Install MeTTaLog Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        pip install numpy==2.2.1
        pip install pyswip janus ansi2html junit2html

        sudo apt-get update

        # Remove existing SWI-Prolog packages to avoid conflicts
        sudo apt-get remove -y swi-prolog-core swi-prolog-nox swi-prolog-x swi-prolog || true
        sudo apt-get install -f -y  # Fix any broken dependencies

        # Attempt to install specific version of swi-prolog-nox (adjust if unavailable)
        sudo dpkg --force-overwrite -i /var/cache/apt/archives/swi-prolog-nox_9.3.25-1-gaf32dae2b-nobleppa2_amd64.deb || true
        sudo apt-get install -y swi-prolog-nox

        # Clone and run INSTALL.sh from logicmoo/metta-wam
        git clone https://github.com/logicmoo/metta-wam --depth 1
        cd metta-wam
        if [ -f "./INSTALL.sh" ]; then
          chmod +x ./INSTALL.sh
          source ./INSTALL.sh --allow-system-modifications
        else
          echo "INSTALL.sh not found in logicmoo/metta-wam. Manual installation required."
          exit 1
        fi
        cd ..

    - name: Run tests using MeTTaLog
      run: |
        mettalog --test examples/tests/unit_test_example.metta
        mettalog --test tests/baseline_compat/metta-morph_tests/tests0.metta
