name: metta-run CI

on:
  push:
    branches:
      - refactor-metta
  pull_request:
    branches:
      - refactor-metta
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Apt Dependencies
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'

    - name: Install MeTTaLog Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        pip install numpy==2.2.1 pyswip janus==1.0.0 ansi2html junit2html

        sudo apt-get update

        # Install build dependencies for SWI-Prolog
        sudo apt-get install -y build-essential autoconf git cmake libpython3-dev libgmp-dev libssl-dev unixodbc-dev \
          libreadline-dev zlib1g-dev libarchive-dev libossp-uuid-dev

        # Remove ALL Prolog-related packages and residual files
        sudo apt-get purge -y 'swi-prolog*' || true
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/lib/swi-prolog /usr/lib/swipl /usr/lib/cmake/swipl || true

        # Install SWI-Prolog 9.3.9 (required by trueagi-io/metta-wam)
        sudo add-apt-repository -y ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt-get install -y swi-prolog-nox=9.3.9-1-g3a1a3b44b-nobleppa2 swi-prolog=9.3.9-1-g3a1a3b44b-nobleppa2

        # Clone and install metta-wam from trueagi-io
        git clone https://github.com/trueagi-io/metta-wam --depth 1
        cd metta-wam
        chmod +x ./INSTALL.sh
        sudo bash ./INSTALL.sh --allow-system-modifications > install.log 2>&1 || { cat install.log; exit 1; }
        cd ..

    - name: Setup MeTTaLog Environment
      run: |
        # Source INSTALL.sh to set up environment variables
        cd metta-wam
        source ./INSTALL.sh --allow-system-modifications > env_setup.log 2>&1 || { cat env_setup.log; exit 1; }
        cd ..

    - name: Verify SWI-Prolog Installation
      run: |
        swipl --version
        if ! command -v swipl &> /dev/null; then
          echo "SWI-Prolog installation failed"
          exit 1
        fi

    - name: Verify MeTTaLog Installation
      run: |
        # Check if mettalog exists
        find / -name mettalog 2>/dev/null || echo "mettalog binary not found"
        if [ -f ./metta-wam/bin/mettalog ]; then
          echo "mettalog found in ./metta-wam/bin"
          sudo mv ./metta-wam/bin/mettalog /usr/local/bin/mettalog
          sudo chmod +x /usr/local/bin/mettalog
        else
          echo "mettalog not found in ./metta-wam/bin"
          exit 1
        fi
        mettalog --version || { echo "mettalog --version failed"; exit 1; }

    - name: Run tests using mettalog
      run: |
        mettalog --test examples/tests/unit_test_example.metta --html || { echo "Unit tests failed"; exit 1; }
        mettalog --test tests/baseline_compat/metta-morph_tests/tests0.metta --html || { echo "Metta-morph tests failed"; exit 1; }