name: metta-run CI

on:
  push:
    branches:
      - refactor-metta
  pull_request:
    branches:
      - refactor-metta
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Install MeTTaLog Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        pip install numpy==2.2.1
        pip install pyswip janus ansi2html junit2html

        sudo apt-get update

        # Remove ALL Prolog-related packages including swi-prolog-core explicitly
        sudo apt-get purge -y swi-prolog-core swi-prolog-nox swi-prolog swi-prolog-x
        sudo apt-get autoremove -y
        sudo apt-get clean

        # Clean up any leftover files
        sudo rm -rf /usr/lib/swi-prolog /usr/lib/cmake/swipl || true

        # Reinstall clean Prolog version (non-conflicting)
        sudo apt-get install -y swi-prolog-nox swi-prolog

        # Clone and run INSTALL.sh from logicmoo/metta-wam
        git clone https://github.com/logicmoo/metta-wam --depth 1
        cd metta-wam

        chmod +x ./INSTALL.sh
        source ./INSTALL.sh --allow-system-modifications  # avoid crashing on minor failures
        cd ..

    - name: Run tests using mettalog
      run: |
        mettalog --test examples/tests/unit_test_example.metta
        mettalog --test tests/baseline_compat/metta-morph_tests/tests0.metta
