name: mettalog CI

on:
  push:
    branches: [main, dev, refactor-metta]
  pull_request:
    branches: [main, dev, refactor-metta]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v2

    - name: Install SWI-Prolog and system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y swi-prolog curl

    - name: Clone and install metta-wam (mettalog)
      run: |
        git clone https://github.com/trueagi-io/metta-wam
        cd metta-wam
        chmod +x INSTALL.sh
        source ./INSTALL.sh --allow-system-modifications --yes

    - name: Add mettalog to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Run mettalog tests
      run: python3 scripts/run-tests.py
