name: metta-run CI

on:
  push:
    branches: [ref/mettalog]
  pull_request:
    branches: [ref/mettalog]
  workflow_dispatch:

jobs:
  mettalog-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y swi-prolog-nox swi-prolog

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run mettalog tests
      run: |
        cd metta-moses/metta-moses/utilities/tests
        mettalog ../lazy-random-selector.metta
