name: metta-run CI

on:
  push:
    branches:
      - refactor-metta
  pull_request:
    branches:
      - refactor-metta
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache Python Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache Apt Dependencies
      uses: actions/cache@v4
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/*.yml') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Setup Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.6'

    - name: Install MeTTaLog Dependencies
      run: |
        python -m pip install --upgrade pip==23.1.2
        pip install numpy==2.2.1 pyswip janus==1.0.0 ansi2html junit2html

        sudo apt-get update

        # Install build dependencies for SWI-Prolog
        sudo apt-get install -y build-essential autoconf git cmake libpython3-dev libgmp-dev libssl-dev unixodbc-dev \
          libreadline-dev zlib1g-dev libarchive-dev libossp-uuid-dev

        # Remove ALL Prolog-related packages and residual files
        sudo apt-get purge -y 'swi-prolog*' || true
        sudo apt-get autoremove -y
        sudo apt-get clean
        sudo rm -rf /usr/lib/swi-prolog /usr/lib/swipl /usr/lib/cmake/swipl || true

        # Explicitly remove conflicting package and file
        sudo dpkg --purge --force-all swi-prolog-core || true
        sudo rm -f /usr/lib/cmake/swipl/SWIPLConfig.cmake || true

        # Install SWI-Prolog 9.3.9+ from PPA
        sudo add-apt-repository -y ppa:swi-prolog/stable
        sudo apt-get update
        apt-cache policy swi-prolog-nox
        sudo apt-get install -y swi-prolog-nox || { echo "SWI-Prolog installation failed"; exit 1; }

        # Clone metta-wam from trueagi-io
        git clone https://github.com/trueagi-io/metta-wam --depth 1
        cd metta-wam
        chmod +x ./INSTALL.sh
        cd ..

    - name: Setup MeTTaLog Environment
      run: |
        # Source INSTALL.sh to set up environment variables
        cd metta-wam
        source ./INSTALL.sh --allow-system-modifications > env_setup.log 2>&1 || { cat env_setup.log; exit 1; }
        cd ..

    - name: Verify SWI-Prolog Installation
      run: |
        swipl --version
        if ! command -v swipl &> /dev/null; then
          echo "SWI-Prolog installation failed"
          exit 1
        fi

    - name: Verify MeTTaLog Installation
      run: |
        # Check if mettalog exists
        find / -name mettalog 2>/dev/null || echoAmend artifact version ID to reflect the updated workflow: `a7f8b9c2-3e4d-4f89-b12a-7c8e9d6f1234` was used in a previous version, so I’ve updated it to a new unique identifier, `f2c4e8a1-5b3e-4f7c-b9e2-9d8f1e3c5678`.