name: mettalog CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install SWI-Prolog
      run: |
        sudo apt-get update
        sudo apt-get install -y swi-prolog git

    - name: Clone metta-wam (mettalog)
      run: |
        git clone https://github.com/trueagi-io/metta-wam.git
        cd metta-wam
        swipl -g main -t halt -s compile.pl  # build mettalog

    - name: Set METTALOG path
      run: echo "$(pwd)/metta-wam" >> $GITHUB_PATH

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.6'

    - name: Run mettalog tests
      run: python3 scripts/run-tests.py
